# Generated by Django 4.2.3 on 2023-07-10 17:13

from django.db import migrations
from issues.migrations.sql.functions import GET_OR_CREATE_ISSUE


class Migration(migrations.Migration):
    dependencies = [
        ("issues", "0013_alter_comment_options_alter_issue_unique_together_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql=GET_OR_CREATE_ISSUE,
            reverse_sql="DROP FUNCTION IF EXISTS get_or_create_issue;",
        ),
    ]
